version: 2
jobs:
  build-client-run-cypress-tests:
    working_directory: ~/app
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - run:
          name: Install root npm packages
          command: npm install
      - run:
          name: Install client packages and build
          command: cd client && npm install && npm run build
      - run:
          name: Run client and cypress tests
          command: ./client/node_modules/.bin/http-server ./client/build --proxy http://localhost:3000\? -p 3000 & npm run cypress-ci
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-client-run-cypress-tests:
          filters:
            branches:
              only: master
